package repast.simphony.gis.display;

public enum MarkProperities {
	SHAPE, NEW_SHAPE, ROTATION, NEW_ROTATION, SIZE_X, NEW_SIZE_X, SIZE_Y, NEW_SIZE_Y, POSITION_X, NEW_POSITION_X, POSITION_Y, NEW_POSITION_Y, COLOR, NEW_COLOR, TRANSPARENCY, NEW_TRANSPARENCY
}
