package repast.simphony.relogo.builder;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
/**
 * Tags a source file as generated by the ReLogoBuilder.
 *   
 * @author jozik
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.SOURCE)
public @interface GeneratedByReLogoBuilder {

}
