package repast.simphony.relogo.builder;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Tags methods generated by ReLogoBuilder with responsible class name.
 * 
 * @author jozik
 * 
 */
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.SOURCE)
public @interface ReLogoBuilderGeneratedFor {
	// Fully qualified classname responsible for generated method
	String value();
}
