/* Generated By:JJTree: Do not edit this line. ASTLinked.java */

package repast.simphony.engine.watcher.query;

import repast.simphony.context.Context;

public class ASTLinked extends SimpleNode {

  public ASTLinked(int id) {
    super(id);
  }

  public ASTLinked(QueryParser p, int id) {
    super(p, id);
  }

	public IBooleanExpression buildExpression(Context context) {
		if (this.children == null) {
			// just a simple linked
			return new LinkedBooleanExpression(context);
		} else {
			ASTName name = (ASTName) children[0];
			return new NamedLinkedBooleanExpression(name.getName(), context);
		}
	}
}
