/* Generated By:JJTree: Do not edit this line. ASTLinkedFrom.java */

package repast.simphony.engine.watcher.query;

import repast.simphony.context.Context;

public class ASTLinkedFrom extends SimpleNode {
  public ASTLinkedFrom(int id) {
    super(id);
  }

  public ASTLinkedFrom(QueryParser p, int id) {
    super(p, id);
  }

	public IBooleanExpression buildExpression(Context context) {
		if (this.children == null) {
			// just a simple linked
			return new LinkedFromBooleanExpression(context);
		} else {
			ASTName name = (ASTName) children[0];
			return new NamedLinkedFromBooleanExpression(name.getName(), context);
		}
	}

}
