/* Generated By:JJTree: Do not edit this line. ASTLinkedTo.java */

package repast.simphony.engine.watcher.query;

import repast.simphony.context.Context;

public class ASTLinkedTo extends SimpleNode {
  public ASTLinkedTo(int id) {
    super(id);
  }

  public ASTLinkedTo(QueryParser p, int id) {
    super(p, id);
  }

	public IBooleanExpression buildExpression(Context context) {
		if (this.children == null) {
			// just a simple linked
			return new LinkedToBooleanExpression(context);
		} else {
			ASTName name = (ASTName) children[0];
			return new NamedLinkedToBooleanExpression(name.getName(), context);
		}
	}

}
