/* Generated By:JJTree: Do not edit this line. ASTNot.java */

package repast.simphony.engine.watcher.query;

import repast.simphony.context.Context;

public class ASTNot extends SimpleNode {
  public ASTNot(int id) {
    super(id);
  }

  public ASTNot(QueryParser p, int id) {
    super(p, id);
  }

	public IBooleanExpression buildExpression(Context context) {
		IBooleanExpression child = ((SimpleNode)this.children[0]).buildExpression(context);
		return new NotBooleanExpression(child);
	}
}
