/* Generated By:JJTree: Do not edit this line. ASTOrExpression.java */

package repast.simphony.engine.watcher.query;

import repast.simphony.context.Context;

public class ASTOrExpression extends SimpleNode {
  public ASTOrExpression(int id) {
    super(id);
  }

  public ASTOrExpression(QueryParser p, int id) {
    super(p, id);
  }

	public IBooleanExpression buildExpression(Context context) {
		IBooleanExpression lhs = ((SimpleNode)this.children[0]).buildExpression(context);
		IBooleanExpression rhs = ((SimpleNode)this.children[1]).buildExpression(context);
		return new OrBooleanExpression(lhs, rhs);
	}
}
