/* Generated By:JJTree: Do not edit this line. ASTWithinMoore.java */

package repast.simphony.engine.watcher.query;

import repast.simphony.context.Context;

public class ASTWithinMoore extends SimpleNode {
  public ASTWithinMoore(int id) {
    super(id);
  }

  public ASTWithinMoore(QueryParser p, int id) {
    super(p, id);
  }

	public IBooleanExpression buildExpression(Context context) {
		ASTNumber num = (ASTNumber) children[0];
		if (this.children.length == 1) {
			return new WithinMooreBooleanExpression(num.getNumber(), context);
		} else {
			ASTName name = (ASTName) children[1];
			return new NamedWithinMooreBooleanExpression(num.getNumber(), name.getName(), context);
		}
	}
}
