/* Generated By:JJTree: Do not edit this line. ASTWithinVN.java */

package repast.simphony.engine.watcher.query;

import repast.simphony.context.Context;

public class ASTWithinVN extends SimpleNode {
  public ASTWithinVN(int id) {
    super(id);
  }

  public ASTWithinVN(QueryParser p, int id) {
    super(p, id);
  }

	public IBooleanExpression buildExpression(Context context) {
		ASTNumber num = (ASTNumber) children[0];
		if (this.children.length == 1) {
			return new WithinVNBooleanExpression(num.getNumber(), context);
		} else {
			ASTName name = (ASTName) children[1];
			return new NamedWithinVNBooleanExpression(num.getNumber(), name.getName(), context);
		}
	}

}
