/* Generated By:JJTree: Do not edit this line. .\QueryParserTreeConstants.java */

package repast.simphony.engine.watcher.query;

public interface QueryParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTANDEXPRESSION = 2;
  public int JJTOREXPRESSION = 3;
  public int JJTNOT = 4;
  public int JJTCOLOCATED = 5;
  public int JJTWITHIN = 6;
  public int JJTWITHINVN = 7;
  public int JJTWITHINMOORE = 8;
  public int JJTLINKED = 9;
  public int JJTLINKEDTO = 10;
  public int JJTLINKEDFROM = 11;
  public int JJTNUMBER = 12;
  public int JJTNAME = 13;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "AndExpression",
    "OrExpression",
    "Not",
    "Colocated",
    "Within",
    "WithinVN",
    "WithinMoore",
    "Linked",
    "LinkedTo",
    "LinkedFrom",
    "Number",
    "Name",
  };
}
