/* Generated By:JJTree&JavaCC: Do not edit this line. QueryParserConstants.java */
package repast.simphony.engine.watcher.query;

public interface QueryParserConstants {

  int EOF = 0;
  int DECNUMBER = 7;
  int FLOAT = 8;
  int EXPONENT = 9;
  int DIGIT = 10;
  int NAME = 11;
  int AND = 12;
  int OR = 13;
  int LINKED = 14;
  int LINKED_FROM = 15;
  int LINKED_TO = 16;
  int COLOCATED = 17;
  int WITHIN = 18;
  int WITHIN_VN = 19;
  int WITHIN_MOORE = 20;
  int NOT = 21;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<DECNUMBER>",
    "<FLOAT>",
    "<EXPONENT>",
    "<DIGIT>",
    "<NAME>",
    "\"and\"",
    "\"or\"",
    "\"linked\"",
    "\"linked_from\"",
    "\"linked_to\"",
    "\"colocated\"",
    "\"within\"",
    "\"within_vn\"",
    "\"within_moore\"",
    "\"not\"",
    "\";\"",
    "\"(\"",
    "\")\"",
  };

}
